# Generated by Django 6.0.4 on 2026-05-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(max_length=50, unique=True, verbose_name='Code barre')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du médicament')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('quantite_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.IntegerField(default=10, verbose_name="Seuil d'alerte")),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicaments/', verbose_name='Image')),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
    ]
