# Generated by Django 6.0.4 on 2026-05-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dosage (ex: 500mg)'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='forme',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forme (comprimé, sirop, etc.)'),
        ),
    ]
