# Generated by Django 6.0.4 on 2026-05-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_medicament_dosage_medicament_forme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('code_fournisseur', models.CharField(max_length=50, unique=True, verbose_name='Code fournisseur')),
                ('email', models.EmailField(max_length=254, verbose_name='Email professionnel')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, verbose_name='Téléphone secondaire')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('pays', models.CharField(default='Maroc', max_length=50, verbose_name='Pays')),
                ('contact_nom', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('contact_fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email direct du contact')),
                ('siret', models.CharField(blank=True, max_length=50, verbose_name='Numéro SIRET')),
                ('tva', models.CharField(blank=True, max_length=50, verbose_name='Numéro TVA')),
                ('categorie_produits', models.CharField(blank=True, help_text='Ex: Antibiotiques, Paracétamol, etc.', max_length=200, verbose_name='Catégories de produits')),
                ('delai_livraison', models.IntegerField(default=3, verbose_name='Délai de livraison (jours)')),
                ('conditions_paiement', models.TextField(blank=True, verbose_name='Conditions de paiement')),
                ('actif', models.BooleanField(default=True, verbose_name='Fournisseur actif')),
                ('note', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
    ]
