# Generated by Django 6.0.4 on 2026-05-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='contact_fonction',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='siret',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='tva',
        ),
    ]
