# Generated by Django 6.0.4 on 2026-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Paiement par carte'), ('livraison', 'Paiement à la livraison'), ('effectue', 'Paiement effectué'), ('en_attente', 'Paiement en attente')], default='livraison', max_length=20),
        ),
    ]
